version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET:-dev-secret-key}
      - DATABASE_URL=sqlite:///texttoimage.db
    volumes:
      - ./static/generated:/app/static/generated
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3